### PR TITLE
Fix F-Droid not displaying app store logo

### PR DESCRIPTION
**Pull request by leoheitmannruiz**
Hello :)

Thanks for KeePassDX!!

It seems F-Droid doesn't display KeePassDX's icon (at least it doesn't for me, at [their website](https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/) and in their client).

As it seems you are using the [fastlane structure](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure), I have copied the [app_store_log.png](https://github.com/Kunzisoft/KeePassDX/blob/master/art/app_store_logo.png) to the appropriate location.

F-Droid seems to have stopped displaying the icon between July 10th and 27th 2023:
https://web.archive.org/web/20230710020311if_/https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/
https://web.archive.org/web/20230729102110if_/https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/
(though this might be a Wayback Machine quirk).

As both those links show the same version of KeePassDX (3.5.1), I assume F-Droid changed something around that time?

Please excuse me in case I've missed something terribly obvious.

Edit: Not sure where the [IzzyOnDroid F-Droid Repository](https://apt.izzysoft.de/fdroid/index/apk/com.kunzisoft.keepass.free) gets the app store logo from. Do you know?

Also, I am confused as to where F-Droid gets the first, third and eleventh screenshot from. See [here](https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/). They aren't contained in this repo, right?

### CODE REVIEW

**Comment by J-Jamet** [comment]
Indeed I saw that, it seems that the logo does not recover correctly. It was deleted at the same time as the old screenshots that were on the F-Droid server but I don't know why the new logo hasn't recovered.

You did retest by compiling with a local F-Droid to see if the logo came back correctly?

**Comment by J-Jamet** [comment]
> Also, I am confused as to where F-Droid gets the first, third and eleventh screenshot from. See [here](https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/). They aren't contained in this repo, right?

https://github.com/Kunzisoft/KeePassDX/blob/master/art/icon.png

**Comment by J-Jamet** [comment]
│   │   ├── icon.png            (app icon, mandatory if your app doesn't include any png icon)

https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/libre/res/mipmap-mdpi/ic_launcher.png

There must be a bug in F-Droid because the source of the icon is in the code (in PNG).

**Comment by J-Jamet** [comment]
In your merge request, you need to export the icon with the square key. And check that the icon is not sent to the Play Store with the fastfile script.

**Comment by shuvashish76** [comment]
I've both the [Libre & Free version](https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-a-libre-and-free-version) installed. Indeed the `free` has `round` key vs `square` for `libre`.

> Not sure where the [IzzyOnDroid F-Droid Repository](https://apt.izzysoft.de/fdroid/index/apk/com.kunzisoft.keepass.free) gets the app store logo from. Do you know?

IG @IzzySoft pick the icon from [here](https://github.com/Kunzisoft/KeePassDX/blob/master/art/app_store_logo.png) not fastlane as no `icon.png` attached there, which is the correct icon for Free version ?

**Comment by IzzySoft** [comment]
If you'd add `icon.png` to `fastlane/metadata/android/en-US/images/`, F-Droid would pick it up automatically. Give me a ping then and I'd do the same for IzzyOnDroid.

**Comment by J-Jamet** [comment]
The problem is that this location is not contextualized according to the flavor, so we can't put the logo of the Free version and the Libre version at the same time.

**Comment by IzzySoft** [comment]
There's the possibility to use flavor-specific fastlane locations. Let me check with my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)…

> For F-Droid, there are 3 possible entry-points the process looks for Fastlane, always located in the root of the app's repository:
>
> * `/fastlane/metadata/android/<locale>/`
> * `/metadata/<locale>/`
> * `/metadata/<packageName>/<locale>`
> * `/src/<buildFlavor>/fastlane/metadata/android/<locale>/`

The last one would match here. I'm not sure though how (identical) content could be shared then between multiple flavors. I don't know if F-Droid supports symlinks there (I guess it does); my updater currently does not. It's on my todo list for quite a while, but I couldn't yet find time to address that… You could try having the "full set" in the current location, and let the "specific elements" (like the icon here) be overwritten from the flavored one. My updater would pull from the main one; I assume F-Droid's would do the same, and then overwrite things it finds in the flavor-specific location. This is not properly documented, though, so I'm not 100% sure.

**Comment by J-Jamet** [comment]
I've just added the icon to the last tree for the "libre" flavor.

**Pull request closed without merging**
