### PR TITLE
Add `JavaVersion` compatible to `icon-pack`

### PR DESCRIPTION
**Pull request by MarijnS95**
This now also contains Kotlin code.

Note that I had to bump all these values to Java 11 or higher to fully make this work, because one of the Gradle plugins requires at least Java 11 but when providing that on my system it runs into a conflict because of these Gradle properties demanding Java (1.)8 (and I am not experienced enough with Java to understand why it has to be so complicated).

### CODE REVIEW

**Comment by J-Jamet** [comment]
If you have a recent JDK version installed, there should be no problem. Here, your commit adds almost nothing, so I'm going to close it. In any case, a complete refactoring of the modules is planned, and the SDK will be migrated in version 4.0.0 of the app.

**Comment by MarijnS95** [comment]
> If you have a recent JDK version installed, there should be no problem.

Unfortunately there is. After installing the latest JDK 20 (on Arch Linux), uninstalling every other version, and making sure it is appropriately used via `archlinux-java fix` (and checked with `archlinux-java {get,status}`, `gradle installLibreRelease` fails with:

```
> Task :app:kaptGenerateStubsLibreReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptGenerateStubsLibreReleaseKotlin'.
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':app:kaptGenerateStubsLibreReleaseKotlin'.
   > Failed to calculate the value of property 'jvmTarget'.
      > Unknown Kotlin JVM target: 20
```

Note that that is with this PR included. Without it, the same complaint appears on `icon-pack` instead:

```
> Task :icon-pack:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':icon-pack:compileReleaseKotlin'.
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':icon-pack:compileReleaseKotlin'.
   > Failed to calculate the value of property 'jvmTarget'.
      > Unknown Kotlin JVM target: 20
```

Are you sure this adds "almost nothing"?

**Comment by J-Jamet** [comment]
The VM for the build environment I use is in openJDK11. I'll make changes if it blocks with F-Droid.

**Comment by MarijnS95** [comment]
> The VM for the build environment I use is in openJDK11.

I've set the same locally, and that keeps clashing with the hard-coded target version 1.8 in `build.gradle` files:

```
* What went wrong:
Execution failed for task ':app:kaptGenerateStubsLibreReleaseKotlin'.
> 'compileLibreReleaseJavaWithJavac' task (current target is 1.8) and 'kaptGenerateStubsLibreReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

> I'll make changes if it blocks with F-Droid.

They [don't seem to be doing anything magical](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.kunzisoft.keepass.libre.yml) to make this work, so it is possibly my own (Arch Linux) environment that is messed up?

**Comment by J-Jamet** [comment]
> They [don't seem to be doing anything magical](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.kunzisoft.keepass.libre.yml) to make this work, so it is possibly my own (Arch Linux) environment that is messed up?

Perhaps I haven't studied the question too much. As I said, I'll make adjustments if there are compilation concerns on F-Droid. In any case, nothing prevents you from making modifications locally  / in your fork so that it compiles on your environment.

**Comment by J-Jamet** [comment]
I've just merged, so it doesn't change anything for me, but if it can be useful in your case, I might as well do it.

**Comment by MarijnS95** [comment]
> Perhaps I haven't studied the question too much. As I said, I'll make adjustments if there are compilation concerns on F-Droid.

It's just a local build, that I expected to work more-or-less out of the box.

> In any case, nothing prevents you from making modifications locally / in your fork so that it compiles on your environment.

Sure, I'll stick with that. Java and me don't go along very well :)

> I've just merged, so it doesn't change anything for me, but if it can be useful in your case, I might as well do it.

Thanks. Yeah as mentioned in the PR description it appears to be needed now that `icon-pack` also contains Kotlin code.

**Pull request merged**
