### PR TITLE
Manage and autofill credit card details

### PR DESCRIPTION
**Pull request by uduerholz**
This is an implementation to resolve issue #525 

Notes:
* String translations are only available for English and German
* Autofill works with Android apps and webviews, if hints are available

### CODE REVIEW

**Comment by J-Jamet** [comment]
Great, thank you for your work, it is really appreciated. ◕‿◕
I will look at your modifications at the beginning of next week to integrate them in the development branch.

**Comment by uduerholz** [comment]
Some more notes:
The credit card details are handles as four custom field entries.

I have tested the autofill feature with the sample app:
https://github.com/android/input-samples/tree/main/AutofillFramework
One test that fails is for "data partitioning":
https://developer.android.com/reference/android/service/autofill/AutofillService?hl=en#data-partitioning
This is not implemented yet. Maybe I can do it in the next days.

The service does not (try to) save new credit card details entered by the user. For autofill to work, the database
needs to already contain them.

**Comment by J-Jamet** [comment]
I just tested your code very briefly.

I think that you should not implement a button to add this type of data directly in the entry edit screen because :

- It's not a single field, it's assimilated to a template. So we should already manage the template system and define the credit card as a selectable template if you want to add this kind of data manually. #https://github.com/Kunzisoft/KeePassDX/issues/191
- If the "Credit Card" template is used, the fields must be filled in directly in the data editing interface. Adding a dialog box is a duplicate and when there are other templates, it will force to create a dialog box for each template, which will be painful. (moreover, it is better to standardize the verification of custom fields in the templates directly in the edit screen. Here the check does not show any error and we do not know why the OK button is no longer clickable.)
- The new add credit card button makes the UI buggy as it is currently made to manage only 3 menu buttons maximum for entry modification.

> https://developer.android.com/reference/android/service/autofill/AutofillService?hl=en#data-partitioning
This is not implemented yet. Maybe I can do it in the next days.

This is not an emergency for me, it can be an autofill in one partition for the moment, we can update the form recognition later.

> The credit card details are handles as four custom field entries

Have you checked with the other KeePass applications if the custom fields related to the credit cards correspond to the ones you defined?  (I haven't looked at it myself yet, that's why I'm asking you.)
Unless custom fields are explicitly linked to an application, harmonizing them to increase compatibility with other solutions would be a good thing.

> The service does not (try to) save new credit card details entered by the user. For autofill to work, the database
needs to already contain them.

Since there is already the autofill registration system, the user should not be lost with this new feature. Ideally, I would prefer to be able to save the elements of a credit card from the autofill even before adding it manually (as it is quite possible to add each custom field one by one).

**Comment by J-Jamet** [comment]
From a technical point of view, here are the first things I noticed : 
- You've done some code duplication. There is no need to recreate specific lists for this type of data. Intrinsically, credit card data is custom data, so there is no need to duplicate views and associated methods. (`creditCardFieldsListView` not needed)
- If you want to handle errors in form fields, it is better to use `TextInputLayout`. Not by adding a color manually to text.
- `month_array` and `year_array` : these numbers do not belong in the list of translation strings. Either you manage a range, or you use methods from date management libraries. In practice, there is no reason to limit the years of a credit card.

I haven't looked at your way of handling credit card autofill yet. I will look at it later.

Regarding the templates, I see a selection system with a drop-down list at the very top of the entry edit screen. But it can be complicated to manage dynamically at first, so we can make a selection of the template before accessing the input edit screen.
The dialog you have created finally contains the rules that we will have to encapsulate in a pseudo language (json if we start with the idea of KeePassXC) which will create the dynamic rules of the template to prebuild the right fields.

**Comment by uduerholz** [comment]
I am not so familiar with the history of this project. There have been some suggestions in the past how to implement the template system, but implementation has not yet started, correct?

I will have a look at the autofill registration system in order to save new credit card details entered by the user.

**Comment by J-Jamet** [comment]
> There have been some suggestions in the past how to implement the template system, but implementation has not yet started, correct?

No, the functionality has not been thought through yet. 
Ideally, the KeePassXC template system would have been identical to the one we are implementing but it is still in the thinking stage. So if we want the functionality, we have to fall back on the template system already present in KeePass2Android (which would allow a backward compatibility). But I have not yet studied its operation, there may be obsolete elements.
It's while looking at your code that I remembered that we have to do the template functionality first to make a generic form interface by theme. Which is not necessarily easy by the way, and not yet standardized that's why I hadn't done it yet.

What you can do is leave the form field code for now by adding the credential fields as normal custom fields with no rules. And we'll talk again when I make the templates. This is planned for version 3.0.0.

**Comment by uduerholz** [comment]
I have now added the possibility to save new credit card details entered by the user and had a look at your comments.

I removed all checks when the user is entering the details manually (can be added later with the template system).
As you noted, month_array and year_array were not in the right place, but are not needed anymore.
I am not sure why creditCardFieldsListView is a code duplicate.
I know, the UI with the additional credit card dialog icon is not optimal, maybe you can decide if you want to place the icon somewhere else or remove it.
I had a look at KeePassXC on Ubuntu, it doesn't seem to have a special credit card entry, so an entry made with
KeePassDX shows up as "additional attributes".
If you like I can push my changes here or make a new pull request.

**Comment by J-Jamet** [comment]
OK thank you.

> I am not sure why creditCardFieldsListView is a code duplicate.

```
    private val creditCardContainerView: View
    private val creditCardFieldsListView: ViewGroup
```
Has the exact same code and methods as : 

```
    private val extraFieldsContainerView: View
    private val extraFieldsListView: ViewGroup
```
It is enough to use the views and methods already present.
As you say :

> I had a look at KeePassXC on Ubuntu, it doesn't seem to have a special credit card entry, so an entry made with
KeePassDX shows up as "additional attributes".


You have copied and pasted all the methods in this section to be CC specific which is not necessary.
The credit card fields are in all cases extras fields ("customs" or "additional attributes" if you want) so no need to make a view section based on the same code.

> I know, the UI with the additional credit card dialog icon is not optimal, maybe you can decide if you want to place the icon somewhere else or remove it.

I will improve the display concept for each template anyway.
When the code will be merged with the template code, it will be a spinner to select the template at the top of the edit screen of an entry.
When "Credit Card" is selected in this spinner, only the fields specific to a credit card will be displayed. So it will replace your add card button.
In case the user wants to add another custom field, the template will automatically switch to "Customization" mode (visible in the spinner).
If another template is selected, the fields that are not usually contained in this template will be deleted (after confirmation from the user) and the fields of the new template will be displayed for editing.

**Comment by J-Jamet** [comment]
If you rebase you can pusher here, we will have the history of the conversation.

**Comment by uduerholz** [comment]
Please have a look at the new commit.

creditCardContainerView and extraFieldsContainerView are separate because I wanted to treat them separately. 
I wanted to have a separate "card view" for the display of the credit card details and also be able to translate the names of the custom fields ("Cardholder", "Credit Card Number", etc.)

**Comment by uduerholz** [comment]
As you know, when data is "auto-saved", the app name or website domain is automatically added to the database entry. For credit card data this is not optimal, as a credit card is normally not app- or website- specific.

**Comment by J-Jamet** [comment]
Don't worry, I won't forget you. I'm just dealing with the bugs and the compatibility with the new KeePass format as a priority.  I'll look your commit as soon as I'm done with those issues.

**Comment by uduerholz** [comment]
No hurry. ;-) Do you plan to release this PR together with a new template system in release 3.0?

**Comment by J-Jamet** [comment]
Yes it's the plan, it will be much more modular if we want to add other types of templates.

**Comment by uduerholz** [comment]
Do you have examples for other templates? I am not sure, if it's "worth" the effort...

**Comment by J-Jamet** [comment]
I'm working on it. I started from your fork and I'm modifying it to add the templates.

The templates are the ones used by the [Keepass plugin](https://github.com/mitchcapper/KPEntryTemplates) and by K2A but I want it to be scalable enough so that a new format (kdbx 5.0 explained in the KeePassXC github) can be added.
A group is defined to contain special entries that define templates.

I still need to make a parser for the group template entries and make the template form generator in the entry edit screen. As I said before, a template will be selectable in the edit screen and will dynamically change the entry form.

I'm far from finished but I can upload the `feature/Templates` (maybe you'll see what I'm getting at) in the evening so that it is at least stable.

**Comment by uduerholz** [comment]
I had a look at the feature/Templates branch. At the moment, I can only select the standard template for a new entry, although I can see references to the credit card template elsewhere in the code.

**Comment by J-Jamet** [comment]
It's just because I haven't done the automatic template creation and the template creation screen yet. But it is possible to create them by hand. Here is a test database : 
[Templates.zip](https://github.com/Kunzisoft/KeePassDX/files/6590026/Templates.zip)

I have to change the code architecture in several places to make it cleaner. Sorry if it takes time, but it's a complicated feature to implement.

**Comment by uduerholz** [comment]
If there is anything I can do to help (tests?) let me now. :-)

**Comment by J-Jamet** [comment]
Yes no problem, I will ask you to test it is planned. ;)

**Comment by uduerholz** [comment]
What's the reason the credit card expiration is stored as exact timestamp? I would prefer an extra data type to just store expiration month and year.

**Comment by J-Jamet** [comment]
Because the template is configured to be linked to the already existing expiration field of an entry.
Here the templates have been generated with KeePass2Android and use the format of the plugin https://github.com/mitchcapper/KPEntryTemplates, I will try to manage a better display when the format is defined only on DATE and not on DATETIME.
Linking the expiration field of an entry allows you to automatically manage the visual display of the expiration (crossed out text, parameters that depend on it, etc.)

**Comment by J-Jamet** [comment]
You can create a template with a separate DATE field if you want.

**Comment by J-Jamet** [comment]
Always keep in mind the compatibility with existing tools, the KeePass format is often used with several clients.

**Comment by uduerholz** [comment]
Okay, I see, thanks.

**Comment by uduerholz** [comment]
I had a more detailed look at the KPEntryTemplates plugin (btw: do you know if it is still maintained?). 
Are the templates "somehow" standardized? For the autofill with KeePassDX to work, we would need to know the field names the templates are actually using. Right?

**Comment by J-Jamet** [comment]
I don't know if it is still maintained but I know that the format is used in KeePass2Android.

> Are the templates "somehow" standardized?

No, That's why I'm trying to make the code modular enough to be compatible with the plugin/kp2a format and the new format planned by KeePassXC.

>  For the autofill with KeePassDX to work, we would need to know the field names the templates are actually using. Right?

Yes at first I would take as a base the labels of the fields autogenerated by Kp2a (in English but which will be translated by the application). Basic templates will already be included in the application to be imported into a database and I will make an associated doc.

**Comment by uduerholz** [comment]
I know you are probably not finished with the implementation, but I wanted to point out some issues I noticed:

- Toggling the templates usage in the database settings creates a new templates group, even if it already exists
- There is no option in the settings to switch to a different templates group
- After editing a credit card entry, the view is not updated (old values are displayed)

**Comment by J-Jamet** [comment]
You do a great job of pointing out things that are wrong. It will allow me to reread the thread and test each point.

> After editing a credit card entry, the view is not updated (old values are displayed)

I'm clearly not done this point, I even opened another local branch to solve other performance problems. And I got to the point of completely redoing the template generation system in a dedicated view. And the fragment will call a ViewModel to synchronize the data.

> Toggling the templates usage in the database settings creates a new templates group, even if it already exists
There is no option in the settings to switch to a different templates group

For the selection of the template group. It's the same way as the recycle bin. The important thing is the UUID of the group, I know that it is not ideal to generate a group and that it would be better to leave the choice to create or to select one. But the full selection requires creating a new node selection module and at this point it will cause more problems than it solves. What I will do at first is to leave the possibility to fill in the UUID of the group to select.

**Comment by J-Jamet** [comment]
I just merged the `feature/Template` branch into the `develop` branch. I improved the recognition of dates for credits card (now days are managed).
However, it seems that with many web browsers, the fields are not recognized because they are not parsed as autofill hints. I'll look later on how to improve this point. Let me know if you like it. Don't hesitate to tell me what's wrong.

**Comment by uduerholz** [comment]
I have checked out the develop branch and the 3.0.0 version looks very nice! I saw a small issue regarding the autofilling of credit card details which I have fixed in my develop branch.

**Comment by uduerholz** [comment]
I did some more tests with the develop branch and have noticed two other issues:

- when creating a new entry and first selecting the wifi template and then selecting another template the custom field for the wifi type is not deleted
- when the custom field _AndroidApp_ is automatically added and saved (after selecting an entry for autofill) the entry loses the information which template it is based on (this is visible when editing the entry later on: e.g. a credit card entry becomes a standard entry)

**Comment by J-Jamet** [comment]
Thank you for the very useful feedback. I note these bugs, I will try to correct them within the week.
I'm also refactoring the database retrieval method for a better architecture and to allow loading several databases but it's also a bit long.

**Comment by uduerholz** [comment]
Some web pages don't provide the autofill hints for credit card forms. I am not sure if there is a good heuristic instead to guess which fields to autofill. My personal opinion is that it's not worth the effort.

**Comment by uduerholz** [comment]
To test my changes I use the "input-samples" from Google. I just pushed an additional testcase to my forked repo:
https://github.com/uduerholz/input-samples
Maybe you are interested. (There are also some other small changes, but this shouldn't distract you.)

**Comment by J-Jamet** [comment]
I have just corrected the 2 bugs you had highlighted.

> Some web pages don't provide the autofill hints for credit card forms. I am not sure if there is a good heuristic instead to guess which fields to autofill. My personal opinion is that it's not worth the effort.

I agree, most browsers don't offer the right hints, there is nothing to do about it unfortunately.

I will do the tests with your repo when I finish all the developments. ;)

**Comment by uduerholz** [comment]
Great. I have a small feature request: It would be nice if the default icon for an entry is also derived from the template.

**Comment by J-Jamet** [comment]
I thought of that but we have to give priority to the origin of the icons because they are already inherited from the group that contains them. I'll have a look at that but I'd like to finish refactoring the retrieval of a database reference first.

**Pull request merged**
