### PR TITLE
Add screenshot mode

### LINKED ISSUE #1354: KeePassDX doesn't work with scrcpy screen mirroring
If I am at home, I prefer to do every phone thing via scrcpy for accessibility reasons, since even the smallest Android phone I could find is way too big for me and I find it a pain to use.

Since Android 12, [scrcpy is unable to display screen content with "secure flags"](https://github.com/Genymobile/scrcpy/issues/2129) and shows a black screen instead.

Since I tend to use open source apps, I have not come across this limitation many times (I think usually apps with DRM or other anti-user features have them); and in the few apps where I encountered that (Signal, browsers' private mode etc.), it was easy to disable in settings. Now that I am looking at using a KeePass client on my phone, I tried KeePassDX first and was immediately greeted with a black screen upon opening the app. So I reached for the phone instead, and tried to find a setting to disable this limitation, but apparently it is not an option at the moment.

I saw in #459 @J-Jamet saying that he "will look to add this request only if another more important reason is mentioned", as screenshots for bug reports are not an important enough use case, and I would agree with that. Screen mirroring issue wasn't present at the time of that thread, since Android allowed shell permissions to capture "protected" screen content at the time; complete blocking of all screen mirroring is new to Android 12. So I am reporting this issue with scrcpy in case my use case is considered important enough to reconsider providing an option.

### PR DESCRIPTION
**Pull request by GianpaMX**
* Add new screenshot mode entry under Settings -> App -> General
* Disable Screenshot mode  by default
* Add a screenshot mode indication at the bottom of the screen
* Set or clear window FLAG_SECURE accordingly
* Translate strings into Spanish

TODO:
* Translate into other languages

resolves #1354

### CODE REVIEW

**Comment by J-Jamet** [comment]
Awesome, thank you, you're fast! I test your code and integrate it tomorrow. :)

**Comment by J-Jamet** [comment]
I just saw it but there is a bug with the lock button on the password generation page.

**Comment by J-Jamet** [comment]
I'm making the fix, it's not a big deal.

**Comment by GianpaMX** [comment]
Oh! Thank you

**Pull request merged**
