### PR TITLE
Let user select entry for autofill

### PR DESCRIPTION
**Pull request by uduerholz**
This is my suggestion to fix issues #943 and #969

### CODE REVIEW

**Comment by J-Jamet** [comment]
Thank you! :) I'll take a look when I finish the templates.

**Comment by J-Jamet** [comment]
I just tested, several things don't work : 
 - The field is not saved in the entry when an entry is selected and the "Save search info" option is activated. The save event is called but nothing is saved.
 - The "Choose entry..." icon remains white and is not tinted.
 - The online suggestion does not offer this new feature

**Comment by uduerholz** [comment]
>     * The field is not saved in the entry when an entry is selected and the "Save search info" option is activated. The save event is called but nothing is saved.

Yes, IIRC the reason is that the search info is empty in this case, otherwise the app would automatically choose an entry that is already linked with the app that is autofilled (if such an entry already exists). I didn't see an "obvious" way how to solve this.

>     * The "Choose entry..." icon remains white and is not tinted.
>     * The online suggestion does not offer this new feature

What do you mean by "online suggestion"?

**Comment by uduerholz** [comment]
Maybe I misunderstood your first point. Did you talk about the AndroidApp custom field?

**Comment by J-Jamet** [comment]
Sorry, I meant inline suggestion. Suggestions that are available in the Google keyboard and not in a popup.

> Maybe I misunderstood your first point. Did you talk about the AndroidApp custom field?

Yes and the URL field.

I know that I'm not easy to understand, but I appreciate the effort, it's always nicer to talk with another dev. :)

**Comment by uduerholz** [comment]
>     * The "Choose entry..." icon remains white and is not tinted.

There is no icon for this entry. ;-)
How do you want to proceed with this and the other two points you mentioned?
I can test with Android 11 only on the emulator, but Gboard does not show
any inline suggestions at all.

**Comment by J-Jamet** [comment]
> There is no icon for this entry. ;-)

OK, this must be the default view, it is necessary to hide the icon in this case (or provide tint one)

> How do you want to proceed with this and the other two points you mentioned?

You have to look at the source code already in place that does the saving, I don't know it by heart, but debugging helps. I'll look at it when I finish my work in progress.

> I can test with Android 11 only on the emulator, but Gboard does not show
any inline suggestions at all.

I also test on emulator, you just have to download the GBoard from Google and activate the "inline autofill" option in KeePassDX.

**Comment by uduerholz** [comment]
I had some trouble getting the inline suggestions to work with the emulator but now it's solved.

**Comment by J-Jamet** [comment]
I am testing your solution.
It works for inline suggestion, that's good.

But the problem is that the manual selection does not automatically save the applicationId in "AndroidApp" or the url as it should to solve #943.
For #969, it's also necessary to make a pagination system to handle a size of more than 10 elements.
I merged your code with the develop branch in  [uduerholz-select_autofill_entry](https://github.com/Kunzisoft/KeePassDX/tree/uduerholz-select_autofill_entry).

I put aside these developments for the moment to focus on the other features of version 3.0.0. It leaves time to make these changes if you want, otherwise I will do it later.

**Comment by uduerholz** [comment]
The manual selection now saves the ApplicationId.
I have merged all changes into my develop branch [uduerholz/KeePassDX/commits/develop](https://github.com/uduerholz/KeePassDX/commits/develop) in the hope that this makes it easier for you to merge back.

**Comment by uduerholz** [comment]
Note: My develop branch also contains small fixes related to the other pull request #946

**Comment by J-Jamet** [comment]
OK, I will try to release a version 3.0.0_beta_01 today. I will look at your code once this version is online.

**Comment by J-Jamet** [comment]
Good job, I just checked, it works fine I just opened a PR with your develop branch to close this one.
I think that we should leave the functionality enabled by default and remove the setting.
I'm modifying your code a bit because the SearchInfo doesn't contain your new variable in the parcelable.
I am also changing the history view if no data found for an open database to be consistent with the new one.

(I also think we can improve the concept by providing the complete list of items matching the search (with the selected one) and not only the newly selected one but can be done later to avoid the big list bug.)

**Pull request closed without merging**
