### PR TITLE
Swap existing icons with font awesome icons

### PR DESCRIPTION
**Pull request by justintime4tea**
Here are some updated icons if you want them. They look good except when they are in the ToolBar (on my fork I've removed the entry icons from toolbar). Alternative to removing the entry icons could be to use the light version of the same icons for toolbar.

No hard feelings if you don't merge in, just want to attempt to contribute back upstream when applicable.

### CODE REVIEW

**Comment by justintime4tea** [comment]
Oh and also you'll find xhdpi, xxhdpi and xxxhdpi support with these icons.

They follow Google material design where by a 32x32 icon has only 24x24 of the image used (rest margins). 64x64 would be 48x48 used, etc...

**Comment by J-Jamet** [comment]
Thank you for the pull request but I'll keep the old icons by default. Adding new icons will be done with a selector. So I keep your icons and I'll integrate them later when the important features are finished. You can also create this icon selector if you want. I was thinking of integrating them as modules. (And if you can make vectors it would be great for the size of the app but it's a bonus ! :) )

Can you tell me why they look not good in the toolbar? (It's the color ?)

**Comment by justintime4tea** [comment]
The dark icons don't look good against the green. On most background colors which aren't white, or really light colored, the dark icons look "off". 

I like the idea of an icon pack and pack selector like you've mentioned in other issues. Perhaps icon packs can support both light and dark variations and the app can do some magic detection of the "lightness" of the toolbar background and "pick the right one"? And/Or even warn user if the icons are white (like in font awesome light) and the background of lists are white? Maybe I'm overthinking it but I love giving the user good experiences lol thanks for the feedback!

**Comment by J-Jamet** [comment]
The color detection can be done with a luminance detection, it may take a little time to develop but it is not a real problem I think. And I'm agree with you, the user experience is the most important. Moreover I looked a little your code, I'm updating KeePass DX according to your elements (all with GPL3, edition in menu and deleting of unused files). I'll update Gradle when I'll have resolved dynamic compilation for < Oreo

**Comment by justintime4tea** [comment]
Thanks for looking at my code. I think I brought the edit back out after reviewing more Google design docs but can't recall. I've been studying the Material design docs more and looking forward to contributing to UI/UX. Thanks for the feedback and for all the work you've already put into KeePassDX.

**Comment by J-Jamet** [comment]
We can select and dynamically import icon packs now, I made a doc to understand the operation. But we should vectorize the icons otherwise it enormously increases the size of the package. (+ 2 Mo if we include 2 packs)

**Pull request merged**
