### PR TITLE
Add Read support for TOTP Tokens

### PR DESCRIPTION
**Pull request by studio315b**
First part of #169.

Provides read support of TOTP tokens in entry page.

TODO:
[ ] Add a way to easily set TOTP tokens
[ ] Add TOTP token to autofill flows

### CODE REVIEW

**Comment by grimpy** [comment]
I did some work to add this to the magic keyboard mostly for personally use

A link to my work
https://github.com/Kunzisoft/KeePassDX/compare/master...grimpy:totp?expand=1

**Comment by J-Jamet** [comment]
I will try to integrate the changes to the beta20 version, as I changed the code now in Kotlin I will have to make a conversion. Sorry for the treatment time, I'm overwhelmed.

**Comment by rodneyrod** [comment]
Anything we could do to help get this code integrated? I'm happy to test binaries and report bugs.

**Comment by J-Jamet** [comment]
I integrated the code with the current version of the application in the branch "feature/TOTP". I noticed a bug in the parse of the url that prevents decrypting an otpauth link.
Continuing the discussion in the issue #70

**Pull request merged**
