### PR TITLE
Create FAQ

### PR DESCRIPTION
**Pull request by yhaulez**
Hello there I love the fact that your project renders such services and I have used it for quite a while now.
You provide by far the safest place to store my passwords but it can to my notice you don't have FAQ on the application. 
And this could really convince newbies that are just downloading the app.  
So I went ahead and created a very informative FAQ for the application.

Including a FAQ on the the application will enlighten users and draw more users, encouraging them to use the application for its diverse purposes.
Please review and merge it. 
Thanks

### CODE REVIEW

**Comment by J-Jamet** [comment]
Super, it was planned but you accelerate things, it is very appreciated! :) I'm going to do the merge and links to access it. Thank you for the contribution!

**Comment by yhaulez** [comment]
Thank you. Am happy you loved it 
Remember to merge it.

**Comment by J-Jamet** [comment]
Don't worry, I'm going to do the merge in my develop branch. This will be visible in github when I'll sync with the server.

**Comment by J-Jamet** [comment]
I'll make a branch with your FAQ formatted in markdown, and my changes, you'll tell me what you think.

**Comment by yhaulez** [comment]
Hello it's me the contributor for your FAQ I just edited the FAQ as you
requested for and this is my gmail. Hope you love the changes.

**Comment by yhaulez** [comment]
Would be lovely my work is to help open source projects and I love it when
they merge my request.

**Comment by J-Jamet** [comment]
OK, I have merged and rebased your commits in FAQ branch : https://github.com/Kunzisoft/KeePassDX/commits/FAQ
If there is no error, I'll merge the FAQ branch in develop and in master for the next release.

**Comment by yhaulez** [comment]
It's is great that way. 
You can go ahead and merge it. Just went through it.

**Comment by J-Jamet** [comment]
As you made this pull request only for steemit, I want to tell you that I do not approve, but if you want to learn programming as you mentioned, I'm ready to see your projects.

**Comment by J-Jamet** [comment]
It will be merged into master branch with the other updates during the release. ;)

**Pull request closed without merging**
