### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper to 6.4.1 using git bash

### 2nd commit
- Update Android Studio to 4.0.0
- Use Kotlin JDK8

### 3rd commit
I manually checked the differences between each version to see what specific usages in the project may have changed. These made it through as good.
- Update bcprov-jdk15on 1.65 -> 1.65.01
- Update joda-time 2.9.9 -> 2.10.6 ([changelog](https://www.joda.org/joda-time/changes-report.html))
- Update commons-collections 3.2.1 -> 3.2.2 ([changelog](https://commons.apache.org/proper/commons-collections/changes-report.html#a3.2.2))
- Update commons-io 1.3.2 -> 2.7 ([changelog](https://commons.apache.org/proper/commons-io/))
- Update commonc-codec 1.11 -> 1.14 ([changelog](https://commons.apache.org/proper/commons-codec/))
- Update junit 4.12 -> 4.13 ([changelog](https://github.com/junit-team/junit4/blob/master/doc/ReleaseNotes4.13.md))

### 4th commit
- Update the FiraMono font file from https://fonts.google.com/specimen/Fira+Mono

### CODE REVIEW

**Comment by J-Jamet** [comment]
Thanks for the pull request. I have to check that the updates don't break anything but it should be good.

**Comment by J-Jamet** [comment]
Crash with API 16 device, maybe commons-io or java-8 requirement:

06-01 12:23:06.692 16603-16629/com.kunzisoft.keepass.free E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:299)
        at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.NoSuchMethodError: java.io.File.toPath
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1336)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:334)
        at com.kunzisoft.keepass.database.element.Database.closeAndClear(Database.kt:495)
        at com.kunzisoft.keepass.database.action.LoadDatabaseRunnable.onStartRun(LoadDatabaseRunnable.kt:52)
        at com.kunzisoft.keepass.tasks.ActionRunnable.run(ActionRunnable.kt:34)
        at com.kunzisoft.keepass.notifications.DatabaseTaskNotificationService$ActionRunnableAsyncTask.doInBackground(DatabaseTaskNotificationService.kt:581)
        at com.kunzisoft.keepass.notifications.DatabaseTaskNotificationService$ActionRunnableAsyncTask.doInBackground(DatabaseTaskNotificationService.kt:567)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
        at java.lang.Thread.run(Thread.java:856)

**Comment by J-Jamet** [comment]
I deleted the _commons-io_ library which was only used by 2 methods and it seems OK.

**Comment by TacoTheDank** [comment]
Great! Thanks :)

**Pull request merged**
