### PR TITLE
Add custom passphrase generator; and separate buttons for PIN-type passwords

### PR DESCRIPTION
**Pull request by patarapolw**
See https://github.com/Kunzisoft/KeePassDX/issues/109

### CODE REVIEW

**Comment by J-Jamet** [comment]
OK Nice! :)
Have you planned to make other changes? Or can I work directly with these commits? As you changed the readme for example, I have to sort the changes.

**Comment by patarapolw** [comment]
I mainly plan to implement Automated Sentence Maker, based on the Keyword List, but that might as well never happen, as as far as I have tried, [it has a very poor performance (at Instantiation)](https://www.reddit.com/r/androiddev/comments/8hsrk3/how_do_i_speed_up_optimize_object_instantiation/).

**Comment by J-Jamet** [comment]
For your sentence maker, It would be necessary to use a thread for the loading, but in all the cases I think that the users don't appreciate much a wait in this place.

I'm going to make a temporary branch based on "develop" to merge and rebase your developments.

**Comment by patarapolw** [comment]
I finished write SentenceMaker, with still an around 5 sec waiting to load, and I can't seem to bypass this wait to Thread.

**Comment by J-Jamet** [comment]
Your code crash for my device, I don't think there is enough memory. It must be viable for small devices.

```
05-09 10:12:16.543 5507-5507/com.kunzisoft.keepass.free E/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 0 free bytes and 3GB until OOM" (recursive case)
05-09 10:12:16.543 5507-5517/com.kunzisoft.keepass.free I/art: WaitForGcToComplete blocked for 68.354ms for cause Alloc
05-09 10:12:16.546 5507-5507/com.kunzisoft.keepass.free E/art: "main" prio=5 tid=1 Runnable
      | group="main" sCount=0 dsCount=0 obj=0x74a97000 self=0x40054828
      | sysTid=5507 nice=-6 cgrp=default sched=0/0 handle=0x40150bec
      | state=R schedstat=( 8532092966 3513630912 10168 ) utm=784 stm=69 core=1 HZ=100
      | stack=0xbe3e2000-0xbe3e4000 stackSize=8MB
      | held mutexes= "mutator lock"(shared held)
        at java.io.BufferedReader.readLine(BufferedReader.java:385)
        at com.patarapolw.randomsentence.SentenceMaker.<init>(SentenceMaker.java:30)
        at com.kunzisoft.keepass.dialogs.GeneratePasswordDialogFragment.lambda$onCreateDialog$0$GeneratePasswordDialogFragment(GeneratePasswordDialogFragment.java:103)
        at com.kunzisoft.keepass.dialogs.GeneratePasswordDialogFragment$$Lambda$0.run(unavailable:0)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5294)
        at java.lang.reflect.Method.invoke!(Native method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by J-Jamet** [comment]
You need to make a thread to load your dialogs, freeze the main UI thread is not a good thing.  You should also use a buffer to read your files.

From a functionality point of view, put seeds to be able to remember passwords I approve!
But here I don't understand how to enter the words of the seed to find the password? It must also be remembered that the goal is to store the items that allow you to connect to your account / to a ftp / wallet cryptocurrency, etc... I think the best thing would be to store the words of the seed as password if it's the way to unlock an element.
Otherwise can you tell me in which case it is useful to generate a password or a pin from a seed in keepass ?

**Comment by patarapolw** [comment]
I ended up using SQLiteAssetHelper, and I believe this should be final for now; unless I integrate NLTK / OpenNLP into the app directly. (Which I can't, because my real device is API level 23; OpenNLP needs level 24; with probably no / worse improvement in performance.

**Comment by patarapolw** [comment]
> Can you rebase your commits ? I don't quite understand what commit does what, many have the same description.

I am bad with git, and I might commit too many times than I should (too small a commit). Also, I don't really know about `rebase`.

Should I commit often on a branch instead? Again, it might take time for me to learn how to branch on both local and GitHub...

I am currently using Android Studio for GitHelper.

**Comment by J-Jamet** [comment]
OK, thanks for the explanantion. I didn't know this method of memorization. That's really great. (I didn't even see that the passwords looked like the words actually! I'm french, it was not immediately obvious as it is not my maternal language)

Good initiative also to have put in a database. It's much better. Do you have links to databases for other languages? Apparently SQLiteAssetHelper is a library that is no longer maintained, I'll look in more detail if it may be a problem in the future.

It now works on my phone with little memory, but there is always the freeze at the launch of the generator and when generating a new password, I have not looked at your code yet, but for every access to long-term data you need a thread (using Runnable, or easier with AsyncTask), here for each operation that called the database.

If you are not comfortable with Git, you can continue on the same branch, my worry is when I'll resume and merge with my development branche. I would not really know what to take and what to change, because I would like to keep both generators (and not replace the old one). Ideally, it would require a system of modules, like KeePass plugins but in a simpler way. I'll think about that.

**Comment by patarapolw** [comment]
Use text file and load everything into memory seems to have a better performance than SQLite, although having a little longer loading time.

Now AsyncTask works, and I move text file loading into the AsyncTask. Not hanging anymore.

All that is left is to make animation in `SentenceMaker loading...`.

**Comment by J-Jamet** [comment]
I'll try to make the modules and merge your code with the new version. It may take time but I want to do things well so that I don't have any bugs.

**Comment by patarapolw** [comment]
Thanks

**Comment by patarapolw** [comment]
Add "Weak" password generator that is of course, easier to remember and copy. Still with bugs, though.

**Comment by J-Jamet** [comment]
Thank you I'll look when I have a little time

**Comment by J-Jamet** [comment]
I tested your modifications and there are some problems : 
 - An exception with a setting key when the app is newly installed
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.kunzisoft.keepass.libre, PID: 9431
                  java.lang.NumberFormatException: For input string: "list_password_generator_choice_key"
                      at java.lang.Integer.parseInt(Integer.java:608)
                      at java.lang.Integer.parseInt(Integer.java:643)
                      at com.kunzisoft.keepass.settings.PreferencesUtil.getDefaultPasswordGenerator(PreferencesUtil.java:70)
                      at com.kunzisoft.keepass.dialogs.GeneratePasswordDialogFragment.onCreateDialog(GeneratePasswordDialogFragment.java:108)
                      at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:328)
                      at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1226)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`
 - The min SDK is minSdkVersion 19 but it would lose users, what is the feature that requires this version?
- The generated APK is now 15MB instead of 6MB (since the master branch) for only one language, English. If we add other languages, it may do too much.

Your passphrase loading system works great, no waiting problem, it's really great!

I have not yet had the time to implement a system of plugins, but it becomes indsensible. I would like users to download only the items they want to use. I absolutely want to integrate and evolve your feature, it is really cool, and add other languages, it would be even better. 
I thought about integrating a plugin store for KeePass DX. If we do things right, everyone can create their extension and integrate it into the basic application with a separate APK. (Like keepass plugins but with an easier-to-use store). The developers will be responsible for updating their plugin and will be able to make updates independently.
There is work but it would solve all the small worries I mentioned, so sorry, I can not integrate your code directly like that in the next version but we can do something really scalable.
What do you think about it ?

**Comment by patarapolw** [comment]
> There is work but it would solve all the small worries I mentioned, so sorry, I can not integrate your code directly like that in the next version but we can do something really scalable. 
> What do you think about it ?

I might plan to remove the sentence creation part (very bad grammar, not very helpful for memorizing), but the passphrase generation part is indispensable for me.

So, I might be able to reduce the file size.

**Comment by patarapolw** [comment]
> Failed to find byte code for android/service/autofill/AutofillService

I tried to add my password generator to your newest edition, and I get this one. Full:

```
java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for android/service/autofill/AutofillService
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.GeneratedMethodAccessor324.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for android/service/autofill/AutofillService
	at com.android.build.gradle.internal.transforms.InstantRunTransform.doTransform(InstantRunTransform.java:312)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.transform(InstantRunTransform.java:178)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 47 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for android/service/autofill/AutofillService
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.doTransform(InstantRunTransform.java:307)
	... 51 more
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for android/service/autofill/AutofillService
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.IOException: Failed to find byte code for android/service/autofill/AutofillService
	at com.android.build.gradle.internal.incremental.AsmUtils.lambda$static$0(AsmUtils.java:89)
	at com.android.build.gradle.internal.incremental.AsmUtils.loadClass(AsmUtils.java:307)
	at com.android.build.gradle.internal.incremental.AsmUtils.readClassAndInterfaces(AsmUtils.java:165)
	at com.android.build.gradle.internal.incremental.AsmUtils.loadClass(AsmUtils.java:278)
	at com.android.build.gradle.internal.incremental.IncrementalVisitor.instrumentClass(IncrementalVisitor.java:342)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.transformToClasses2Format(InstantRunTransform.java:406)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.lambda$doTransform$3(InstantRunTransform.java:268)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.lambda$null$4(InstantRunTransform.java:297)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	... 4 more
```

**Comment by patarapolw** [comment]
I make it no conflict, but I cannot get multiple passwordGeneratorDialogs to work:-

https://github.com/patarapolw/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/activities/EntryEditActivity.java#L244

Also, hard-coding int 2, 3 isn't very graceful.

**Comment by J-Jamet** [comment]
I also had this error and after upgraded the emulators and android studio, she disappeared. I also use old emulators to test. It is possible that this is also a bug in the instant run (I deleted libraries manually to make room and when I compile without instant run it works), it must be a bug of google.
Great for your update, I was just going to look at how to integrate it to make the two managers live together.

**Comment by J-Jamet** [comment]
I can not launch the generator, it crash every time on my Galaxy S2 :

```
07-29 10:03:04.094 7542-7542/com.kunzisoft.keepass.pro E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kunzisoft.keepass.pro, PID: 7542
    java.lang.NumberFormatException: For input string: "list_password_generator_choice_key"
        at java.lang.Integer.parseInt(Integer.java:521)
        at java.lang.Integer.parseInt(Integer.java:556)
        at com.kunzisoft.keepass.settings.PreferencesUtil.getDefaultPasswordGenerator(PreferencesUtil.java:70)
        at com.kunzisoft.keepass.activities.EntryEditActivity.openPasswordGenerator(EntryEditActivity.java:243)
        at com.kunzisoft.keepass.activities.EntryEditActivity.lambda$onCreate$1$EntryEditActivity(EntryEditActivity.java:218)
        at com.kunzisoft.keepass.activities.EntryEditActivity$$Lambda$1.onClick(Unknown Source)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by patarapolw** [comment]
It seems that a password generator has to be chosen on the first time (in Settings). I'll find a way to solve this bug.

**Comment by patarapolw** [comment]
How do I take the screenshot of my custom password generators?

It says

> System UI
> Couldn't capture screenshot
> Screenshots are not allowed by this app or your organization

**Comment by patarapolw** [comment]
Is it OK to share this on https://www.reddit.com/r/coolgithubprojects/ along with the APK (see https://github.com/patarapolw/KeePassDX-diceware#installation)

**Comment by patarapolw** [comment]
BTW, do you plan to officially add Passphrase option? I don't really mean my version, but KeepassXC seems to allow this kind of stuff officially.

screen shot 2018-12-03 at 22 43 08

**Comment by J-Jamet** [comment]
Yes it is planned, I just do not have the time right now, I am with a customer contract but I will have more time at the end of December. Your pull request is not yet integrated because there are many changes.

**Comment by patarapolw** [comment]
I am moving away to BitWarden, as it has Passphrase option on both macOS and Android.

However, if syncing the `*.kbdx`, rather than relying on cloud database is possible and reliable, I should reconsider KeePassDX.

https://github.com/Kunzisoft/KeePassDX/issues/560

**Comment by J-Jamet** [comment]
I understand very well. Thank you very much for your work in any case, I will keep you informed of the evolution of the passphrases manager and I will convert your work to the new code.
There are a lot of other topics to cover but when I work on it, it will be thoroughly. ;)

**Review by Karolina241 — APPROVED** [review]

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Did you take eff's large word list?

https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt

**Comment by J-Jamet** [comment]
Passphrase is now implemented in development. Sorry for the delay, I'm aware that it was a wanted feature and you were invested in it so thanks a lot. But I prefered to use an existing library and to get as close as possible to the KeePassXC features, if you want me to implement additional features that you had developed, we can discuss about it. I close this issue, thanks for your work.
#218
https://github.com/Kunzisoft/KeePassDX/commit/76f9e8ec6eea2956909364f556257e3294dc378d

**Pull request closed without merging**
